- name: vars playbook
  hosts: localhost
  vars:
    NAME: Sivakumar
  tasks:
  - name: var from play level
    debug:
      msg: "Hello {{NAME}}"
  - name: var from task level
    vars:
      NAME: Sivakumar Reddy
    debug:
      msg: "Hello {{NAME}}"
