- name: variables from prompt
  hosts: localhost
  vars_prompt:
  - name : PASSWD
    prompt : Please enter the password
    private : no
  tasks:
  - name: test the prompt password
    debug:
      msg: "password entered is: {{PASSWD}}"