- name: roboshop web component
  become: yes
  hosts: localhost
  tasks:
  - name: install nginx server
    ansible.builtin.yum:
      name: nginx
      state: installed
  - name: enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: true
  - name: remove the default website
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent