- name: roboshop web component
  become: yes
  hosts: localhost
  tasks:
  - name: install nginx server
    ansible.builtin.yum:
      name: nginx
      state: installed
  - name: enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: true
  - name: remove the default website
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent
  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory
  - name: Unarchive a file that needs to be downloaded (added in 2.0)
    ansible.builtin.unarchive:
      src: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /tmp/
      remote_src: yes